"""Declarative base, naming conventions, and the shared money and timestamp conventions.

Three project-wide rules are enforced here rather than repeated per table.

**Money is never binary floating point.** Every monetary column is
``NUMERIC(MONEY_PRECISION, MONEY_SCALE)`` mapped to Python ``Decimal`` with
``asdecimal=True``. ``Float``/``REAL``/``DOUBLE PRECISION`` must never appear in this
package, and a test asserts their absence across the whole metadata rather than trusting
review. Scale is fixed at 4 so every ISO 4217 minor unit fits without rounding — JPY has 0
minor digits, most currencies 2, and a few (BHD, KWD, TND) have 3, while intermediate
fee-split and FX values commonly need a fourth. Persisting at a coarser scale would round
silently at the storage boundary, which is exactly the failure this project exists to avoid.

**Currency is explicit wherever an amount exists.** Amounts are always declared with a
paired currency column and a check constraint tying the two together, so no row can hold a
number whose unit is unknown.

**Timestamps are timezone-aware, with explicit ownership.** Row-lifecycle columns
(``created_at``) are generated by the *database* via ``server_default=now()``, so a row
cannot exist without one even if inserted outside the application. Business timestamps —
when a batch was received, when a ledger entry was booked — are supplied by the
*application*, because only it knows the real-world event time. Naive datetimes are
rejected by ``TIMESTAMP(timezone=True)``.
"""

from __future__ import annotations

import datetime as dt
import uuid
from typing import Any, Final

from sqlalchemy import CheckConstraint, DateTime, MetaData, Numeric, String, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Total digits and digits after the point for every monetary column. See the module
#: docstring for why the scale is 4 and not 2.
MONEY_PRECISION: Final = 20
MONEY_SCALE: Final = 4

#: ISO 4217 alphabetic code length.
CURRENCY_CODE_LENGTH: Final = 3

#: Deterministic constraint and index names. Without this, autogenerated migrations produce
#: database-assigned names that differ between environments, and a constraint cannot be
#: referenced reliably in a downgrade.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base carrying the shared metadata and naming convention."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def money_column(**kwargs: Any) -> Mapped[Any]:
    """A monetary amount: exact ``NUMERIC``, never floating point.

    Callers must pair this with :func:`currency_column` and a check constraint; the
    convention is not optional, and :func:`currency_pairing_constraint` builds the check.
    """
    return mapped_column(
        Numeric(precision=MONEY_PRECISION, scale=MONEY_SCALE, asdecimal=True),
        **kwargs,
    )


def currency_column(**kwargs: Any) -> Mapped[Any]:
    """An ISO 4217 alphabetic currency code, stored as a fixed-length string."""
    return mapped_column(String(CURRENCY_CODE_LENGTH), **kwargs)


def currency_format_constraint(column: str, name: str) -> CheckConstraint:
    """Reject anything that is not three upper-case letters.

    In the database rather than the application because a currency code arriving through a
    migration, a bulk load or a future service still has to be a currency code.
    """
    return CheckConstraint(f"{column} ~ '^[A-Z]{{3}}$'", name=name)


def currency_pairing_constraint(amount: str, currency: str, name: str) -> CheckConstraint:
    """An amount and its currency are both present or both absent — never one alone.

    A number without a unit is financially ambiguous, and a currency without a number is
    meaningless. This is the invariant that keeps nullable money columns honest.
    """
    return CheckConstraint(
        f"({amount} IS NULL) = ({currency} IS NULL)",
        name=name,
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key: application-generated UUIDv4.

    Generated in Python rather than by the database so an identifier exists before the row
    is flushed — later increments correlate identifiers across logs, evidence references
    and audit events, and waiting for a sequence would make that awkward. UUIDs also avoid
    exposing row counts through enumerable ids.
    """
    return mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


def created_at_column() -> Mapped[dt.datetime]:
    """Row-creation timestamp, **generated by the database**.

    ``server_default`` rather than a Python default so the column is populated even for
    rows inserted outside the application — a migration, a bulk load, or psql.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
