"""exception, outbox, DLQ and audit schema

Adds the control and reliability half of the schema (increment M1.2): the exception record
and its evidence, the model proposal, the human approval, the computed adjustment, and the
four tables that make an irreversible financial write recoverable — ``outbox``,
``posting_attempt``, ``dlq`` and ``recovery_queue`` — plus the append-only ``audit_event``.

Two things here are **not** autogenerate output, and they are the reason this file was
reviewed by hand rather than accepted as produced:

1. ``Money`` is a custom type. Autogenerate emitted
   ``ledger_exception_control_plane.db.base.Money()`` but did not emit the import for it, so
   the generated file raised ``NameError`` on execution. The import below is required, not
   cosmetic.
2. Alembic cannot see a trigger. ``audit_event`` is append-only, and the enforcement is a
   trigger added at the end of ``upgrade`` — see the note there for why a grant alone was not
   considered sufficient.

Everything else is autogenerate output, checked line by line against the models for
foreign-key delete semantics, constraint names, partial index predicates and the monetary
constraints inherited from ``a72a14e6f51f``.

Two check constraints carry an explicit ``IS NOT NULL`` that looks redundant and is not.
``NULL IN (...)`` evaluates to NULL, and PostgreSQL treats a NULL check result as satisfied,
so ``state <> 'settled' OR last_outcome IN ('confirmed', 'rejected')`` admits a settled row
with no outcome at all. Both were written that way, both passed review by reading, and both
were caught only by a test that inserted the row.

Three foreign keys are composite, which autogenerate renders faithfully but which are worth
naming here because they are load-bearing rather than structural. ``adjustment`` references
``(approval.id, approved_treatment, principal)`` so that an adjustment cannot be authorised
by a rejection — a rejection has ``approved_treatment IS NULL`` and the referencing column is
NOT NULL, so no such row can exist. ``posting_attempt`` references
``(adjustment.id, operation_id)`` so the operation identifier on an attempt record is
verified rather than copied. ``recovery_queue`` references
``(adjustment.id, approving_principal)`` so the segregation-of-duties check compares against
the real approver.

Revision ID: 133ac0053abd
Revises: a72a14e6f51f
Create Date: 2026-08-29 17:41:11.111443
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import ledger_exception_control_plane.db.base

revision: str = "133ac0053abd"
down_revision: str | None = "a72a14e6f51f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("principal", sa.String(length=128), nullable=False),
        sa.Column("agent_identity", sa.String(length=128), nullable=True),
        sa.Column("tool", sa.String(length=24), nullable=False),
        sa.Column("scope_granted", sa.String(length=256), nullable=False),
        sa.Column("approval_decision", sa.String(length=16), nullable=False),
        sa.Column("approver", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("region_jurisdiction", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "approval_decision IN ('approved', 'rejected', 'edited', 'n_a')",
            name=op.f("ck_audit_event_approval_decision_valid"),
        ),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure', 'abstained', 'quarantined')",
            name=op.f("ck_audit_event_outcome_valid"),
        ),
        sa.CheckConstraint(
            "tool IN ('match', 'propose_treatment', 'approve', 'compute_amount', 'post', "
            "'retry', 'dlq', 'replay')",
            name=op.f("ck_audit_event_tool_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(
        "ix_audit_event_correlation_id_occurred_at",
        "audit_event",
        ["correlation_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "exception",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("settlement_line_id", sa.UUID(), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification IN ('partial_capture', 'fee_split', 'chargeback_reversal', "
            "'fx_rounding', 'cross_period_refund', 'unclassified')",
            name=op.f("ck_exception_classification_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved')", name=op.f("ck_exception_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["settlement_line_id"],
            ["settlement_line.id"],
            name=op.f("fk_exception_settlement_line_id_settlement_line"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exception")),
        sa.UniqueConstraint("settlement_line_id", name="uq_exception_settlement_line_id"),
    )
    op.create_index(
        "ix_exception_status_created_at", "exception", ["status", "created_at"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exception_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_ref", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('dispute_reason', 'merchant_memo', 'support_ticket_note', "
            "'remittance_reference', 'candidate_ledger_entry')",
            name=op.f("ck_evidence_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exception.id"],
            name=op.f("fk_evidence_exception_id_exception"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index("ix_evidence_exception_id", "evidence", ["exception_id"], unique=False)
    op.create_table(
        "treatment_proposal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exception_id", sa.UUID(), nullable=False),
        sa.Column("treatment", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("cassette_id", sa.String(length=128), nullable=True),
        sa.Column("region_jurisdiction", sa.String(length=64), nullable=False),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT abstained OR treatment = 'escalate'",
            name=op.f("ck_treatment_proposal_abstention_escalates"),
        ),
        sa.CheckConstraint(
            "confidence IN ('low', 'medium', 'high')",
            name=op.f("ck_treatment_proposal_confidence_valid"),
        ),
        sa.CheckConstraint(
            "prompt_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_treatment_proposal_prompt_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "treatment IN ('rebook', 'accrue', 'write_off', 'escalate')",
            name=op.f("ck_treatment_proposal_treatment_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exception.id"],
            name=op.f("fk_treatment_proposal_exception_id_exception"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treatment_proposal")),
    )
    op.create_index(
        "ix_treatment_proposal_exception_id", "treatment_proposal", ["exception_id"], unique=False
    )
    op.create_table(
        "approval",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exception_id", sa.UUID(), nullable=False),
        sa.Column("resolution_version", sa.Integer(), nullable=False),
        sa.Column("treatment_proposal_id", sa.UUID(), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("approved_treatment", sa.String(length=16), nullable=True),
        sa.Column("principal", sa.String(length=128), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(decision IN ('approved', 'edited')) = (approved_treatment IS NOT NULL)",
            name=op.f("ck_approval_approved_treatment_iff_authorising"),
        ),
        sa.CheckConstraint(
            "approved_treatment IS NULL OR approved_treatment IN ('rebook', 'accrue', 'write_off', "
            "'escalate')",
            name=op.f("ck_approval_approved_treatment_valid"),
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected', 'edited')",
            name=op.f("ck_approval_decision_valid"),
        ),
        sa.CheckConstraint(
            "resolution_version >= 1", name=op.f("ck_approval_resolution_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exception.id"],
            name=op.f("fk_approval_exception_id_exception"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["treatment_proposal_id"],
            ["treatment_proposal.id"],
            name=op.f("fk_approval_treatment_proposal_id_treatment_proposal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval")),
        sa.UniqueConstraint(
            "exception_id", "resolution_version", name="uq_approval_exception_resolution_version"
        ),
        sa.UniqueConstraint(
            "id", "approved_treatment", "principal", name="uq_approval_id_treatment_principal"
        ),
    )
    op.create_table(
        "treatment_proposal_evidence",
        sa.Column("treatment_proposal_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_treatment_proposal_evidence_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["treatment_proposal_id"],
            ["treatment_proposal.id"],
            name=op.f("fk_treatment_proposal_evidence_treatment_proposal_id_treatment_proposal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "treatment_proposal_id", "evidence_id", name=op.f("pk_treatment_proposal_evidence")
        ),
    )
    op.create_table(
        "adjustment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("approval_id", sa.Uuid(), nullable=False),
        sa.Column("approved_treatment", sa.String(length=16), nullable=False),
        sa.Column("approving_principal", sa.String(length=128), nullable=False),
        sa.Column("amount", ledger_exception_control_plane.db.base.Money(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("account_code", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("operation_id", sa.String(length=64), nullable=False),
        sa.Column("instruction_payload_hash", sa.String(length=64), nullable=False),
        sa.Column("posting_ref", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount <> 'NaN'::numeric AND trunc(amount, 4) = amount",
            name=op.f("ck_adjustment_amount_scale"),
        ),
        sa.CheckConstraint(
            "approved_treatment <> 'escalate'",
            name=op.f("ck_adjustment_escalation_is_never_posted"),
        ),
        sa.CheckConstraint(
            "approved_treatment IN ('rebook', 'accrue', 'write_off', 'escalate')",
            name=op.f("ck_adjustment_treatment_valid"),
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_adjustment_currency_format")),
        sa.CheckConstraint(
            "instruction_payload_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_adjustment_instruction_payload_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "operation_id ~ '^[0-9a-f]{64}$'", name=op.f("ck_adjustment_operation_id_is_sha256_hex")
        ),
        sa.CheckConstraint(
            "period ~ '^[0-9]{4}-[0-9]{2}$'", name=op.f("ck_adjustment_period_is_year_month")
        ),
        sa.CheckConstraint(
            "abs(amount) < 10000000000000000", name=op.f("ck_adjustment_amount_magnitude")
        ),
        sa.ForeignKeyConstraint(
            ["approval_id", "approved_treatment", "approving_principal"],
            ["approval.id", "approval.approved_treatment", "approval.principal"],
            name="fk_adjustment_approval",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adjustment")),
        sa.UniqueConstraint("approval_id", name="uq_adjustment_approval_id"),
        sa.UniqueConstraint(
            "id", "approving_principal", name="uq_adjustment_id_approving_principal"
        ),
        sa.UniqueConstraint("id", "operation_id", name="uq_adjustment_id_operation_id"),
        sa.UniqueConstraint("operation_id", name="uq_adjustment_operation_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("adjustment_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("last_outcome", sa.String(length=24), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_outcome IS NULL OR last_outcome IN ('confirmed', 'rejected', 'throttled', "
            "'unknown', 'partially_applied')",
            name=op.f("ck_outbox_last_outcome_valid"),
        ),
        sa.CheckConstraint(
            "state <> 'settled' OR (last_outcome IS NOT NULL AND last_outcome IN ('confirmed', "
            "'rejected'))",
            name=op.f("ck_outbox_settled_requires_terminal_outcome"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'settled', 'dead_lettered')", name=op.f("ck_outbox_state_valid")
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_outbox_attempt_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["adjustment.id"],
            name=op.f("fk_outbox_adjustment_id_adjustment"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
        sa.UniqueConstraint("adjustment_id", name="uq_outbox_adjustment_id"),
    )
    op.create_index(
        "ix_outbox_pending_next_attempt_at",
        "outbox",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_table(
        "posting_attempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("adjustment_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.String(length=64), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posting_ref", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'resolved') = (outcome IS NOT NULL AND resolved_at IS NOT NULL)",
            name=op.f("ck_posting_attempt_resolved_iff_outcome_recorded"),
        ),
        sa.CheckConstraint(
            "operation_id ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_posting_attempt_operation_id_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('confirmed', 'rejected', 'throttled', 'unknown', "
            "'partially_applied')",
            name=op.f("ck_posting_attempt_outcome_valid"),
        ),
        sa.CheckConstraint(
            "posting_ref IS NULL OR (outcome IS NOT NULL AND "
            "outcome IN ('confirmed', 'partially_applied'))",
            name=op.f("ck_posting_attempt_posting_ref_requires_applied_outcome"),
        ),
        sa.CheckConstraint(
            "state IN ('in_flight', 'resolved')", name=op.f("ck_posting_attempt_state_valid")
        ),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_posting_attempt_attempt_no_positive")),
        sa.CheckConstraint(
            "resolved_at IS NULL OR resolved_at >= sent_at",
            name=op.f("ck_posting_attempt_resolved_after_sent"),
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_id", "operation_id"],
            ["adjustment.id", "adjustment.operation_id"],
            name="fk_posting_attempt_adjustment",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posting_attempt")),
        sa.UniqueConstraint("adjustment_id", "attempt_no", name="uq_posting_attempt_adjustment_no"),
    )
    op.create_index(
        "ix_posting_attempt_in_flight",
        "posting_attempt",
        ["sent_at"],
        unique=False,
        postgresql_where=sa.text("state = 'in_flight'"),
    )
    op.create_table(
        "recovery_queue",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("adjustment_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_procedure", sa.Text(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approving_principal", sa.String(length=128), nullable=False),
        sa.Column("resolution", sa.String(length=32), nullable=True),
        sa.Column("resolved_by", sa.String(length=128), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'resolved') = (resolution IS NOT NULL AND resolved_by IS NOT NULL "
            "AND resolved_at IS NOT NULL)",
            name=op.f("ck_recovery_queue_resolved_iff_fully_recorded"),
        ),
        sa.CheckConstraint(
            "resolution IS NULL OR resolution IN ('confirmed_by_evidence', 'rejected_by_evidence', "
            "'resolved_unverified')",
            name=op.f("ck_recovery_queue_resolution_valid"),
        ),
        sa.CheckConstraint(
            "state IN ('open', 'resolved')", name=op.f("ck_recovery_queue_state_valid")
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR resolved_at >= opened_at",
            name=op.f("ck_recovery_queue_resolved_after_opened"),
        ),
        sa.CheckConstraint(
            "resolved_by IS NULL OR resolved_by <> approving_principal",
            name=op.f("ck_recovery_queue_segregation_of_duties"),
        ),
        sa.CheckConstraint(
            "sla_due_at > opened_at", name=op.f("ck_recovery_queue_sla_due_after_opened")
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_id", "approving_principal"],
            ["adjustment.id", "adjustment.approving_principal"],
            name="fk_recovery_queue_adjustment",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_queue")),
    )
    op.create_index(
        "ix_recovery_queue_open_sla_due_at",
        "recovery_queue",
        ["sla_due_at"],
        unique=False,
        postgresql_where=sa.text("state = 'open'"),
    )
    op.create_index(
        "uq_recovery_queue_open_adjustment",
        "recovery_queue",
        ["adjustment_id"],
        unique=True,
        postgresql_where=sa.text("state = 'open'"),
    )
    op.create_table(
        "dlq",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("outbox_id", sa.UUID(), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("replay_state", sa.String(length=16), nullable=False),
        sa.Column("replayed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(replay_state = 'replayed') = (replayed_at IS NOT NULL)",
            name=op.f("ck_dlq_replayed_at_iff_replayed"),
        ),
        sa.CheckConstraint(
            "NOT (envelope ?| array['amount','value','total','sum','qty','quantity',"
            "'rate','pct','percent','balance','delta','fee','price','cost'])",
            name=op.f("ck_dlq_envelope_carries_no_monetary_key"),
        ),
        sa.CheckConstraint(
            "replay_state IN ('pending', 'replayed', 'abandoned')",
            name=op.f("ck_dlq_replay_state_valid"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_dlq_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["outbox_id"], ["outbox.id"], name=op.f("fk_dlq_outbox_id_outbox"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dlq")),
        sa.UniqueConstraint("outbox_id", name="uq_dlq_outbox_id"),
    )
    op.create_index(
        "ix_dlq_pending_created_at",
        "dlq",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("replay_state = 'pending'"),
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------------------
    # audit_event is append-only.
    #
    # Enforced by a trigger rather than by privileges. A grant-based control protects
    # only the roles someone remembered to restrict, and it does not apply to the table
    # owner at all — which is exactly the role a migration or a maintenance script runs
    # as. The trigger refuses UPDATE, DELETE and TRUNCATE regardless of who is asking.
    #
    # Honest about its limit: the table owner can still drop the trigger. This stops
    # accidental and application-level mutation, not a deliberate privileged operator.
    # Restricting the deployed application role to SELECT and INSERT is a deployment
    # concern (increment 10.1) and is complementary, not a substitute.
    # ------------------------------------------------------------------------------
    op.execute(
        sa.text(
            """
            CREATE FUNCTION audit_event_reject_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION
                    'audit_event is append-only; % is not permitted', TG_OP
                    USING ERRCODE = 'restrict_violation';
            END;
            $$;
            """
        )
    )
    op.execute(
        sa.text(
            """
            CREATE TRIGGER audit_event_append_only_row
            BEFORE UPDATE OR DELETE ON audit_event
            FOR EACH ROW EXECUTE FUNCTION audit_event_reject_mutation();
            """
        )
    )
    # TRUNCATE bypasses row-level triggers entirely, so an append-only table that permits
    # it is not append-only. Statement-level trigger, because TRUNCATE has no rows.
    op.execute(
        sa.text(
            """
            CREATE TRIGGER audit_event_append_only_truncate
            BEFORE TRUNCATE ON audit_event
            FOR EACH STATEMENT EXECUTE FUNCTION audit_event_reject_mutation();
            """
        )
    )


def downgrade() -> None:
    # Triggers first. Dropping the table would remove them implicitly, but the function is
    # schema-level and would survive, so a later re-upgrade would fail on a name that already
    # exists. Explicit drops keep upgrade/downgrade/re-upgrade genuinely repeatable.
    op.execute(sa.text("DROP TRIGGER IF EXISTS audit_event_append_only_truncate ON audit_event"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS audit_event_append_only_row ON audit_event"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS audit_event_reject_mutation()"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_dlq_pending_created_at",
        table_name="dlq",
        postgresql_where=sa.text("replay_state = 'pending'"),
    )
    op.drop_table("dlq")
    op.drop_index(
        "uq_recovery_queue_open_adjustment",
        table_name="recovery_queue",
        postgresql_where=sa.text("state = 'open'"),
    )
    op.drop_index(
        "ix_recovery_queue_open_sla_due_at",
        table_name="recovery_queue",
        postgresql_where=sa.text("state = 'open'"),
    )
    op.drop_table("recovery_queue")
    op.drop_index(
        "ix_posting_attempt_in_flight",
        table_name="posting_attempt",
        postgresql_where=sa.text("state = 'in_flight'"),
    )
    op.drop_table("posting_attempt")
    op.drop_index(
        "ix_outbox_pending_next_attempt_at",
        table_name="outbox",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_table("outbox")
    op.drop_table("adjustment")
    op.drop_table("treatment_proposal_evidence")
    op.drop_table("approval")
    op.drop_index("ix_treatment_proposal_exception_id", table_name="treatment_proposal")
    op.drop_table("treatment_proposal")
    op.drop_index("ix_evidence_exception_id", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index("ix_exception_status_created_at", table_name="exception")
    op.drop_table("exception")
    op.drop_index("ix_audit_event_correlation_id_occurred_at", table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
