"""core reconciliation schema

Revision ID: cf6581793e0c
Revises:
Create Date: 2026-08-29 13:16:56.294671
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cf6581793e0c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_ref", sa.String(length=128), nullable=False),
        sa.Column("account_code", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_ledger_entry_currency_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entry")),
        sa.UniqueConstraint("external_ref", name="uq_ledger_entry_external_ref"),
    )
    op.create_index(
        "ix_ledger_entry_account_code_booked_at",
        "ledger_entry",
        ["account_code", "booked_at"],
        unique=False,
    )
    op.create_table(
        "settlement_batch",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("raw_payload", sa.LargeBinary(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("quarantine_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'quarantined') = (quarantine_reason IS NOT NULL)",
            name=op.f("ck_settlement_batch_quarantine_reason_iff_quarantined"),
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_settlement_batch_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "status IN ('received', 'parsed', 'quarantined')",
            name=op.f("ck_settlement_batch_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_batch")),
        sa.UniqueConstraint("content_hash", name="uq_settlement_batch_content_hash"),
    )
    op.create_table(
        "settlement_line",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("settlement_batch_id", sa.UUID(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("psp_reference", sa.String(length=128), nullable=False),
        sa.Column("merchant_reference", sa.String(length=128), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=False),
        sa.Column("match_state", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_settlement_line_currency_format")
        ),
        sa.CheckConstraint(
            "match_state IN ('unmatched', 'matched')",
            name=op.f("ck_settlement_line_match_state_valid"),
        ),
        sa.CheckConstraint("line_number > 0", name=op.f("ck_settlement_line_line_number_positive")),
        sa.ForeignKeyConstraint(
            ["settlement_batch_id"],
            ["settlement_batch.id"],
            name=op.f("fk_settlement_line_settlement_batch_id_settlement_batch"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_line")),
        sa.UniqueConstraint(
            "settlement_batch_id", "line_number", name="uq_settlement_line_batch_line_number"
        ),
    )
    op.create_index(
        "ix_settlement_line_batch_match_state",
        "settlement_line",
        ["settlement_batch_id", "match_state"],
        unique=False,
    )
    op.create_table(
        "match_result",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("settlement_line_id", sa.UUID(), nullable=False),
        sa.Column("ledger_entry_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("tolerance_applied", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("tolerance_currency", sa.String(length=3), nullable=True),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tolerance_currency IS NULL OR tolerance_currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_match_result_tolerance_currency_format"),
        ),
        sa.CheckConstraint(
            "(tolerance_applied IS NULL) = (tolerance_currency IS NULL)",
            name=op.f("ck_match_result_tolerance_currency_pairing"),
        ),
        sa.CheckConstraint(
            "tolerance_applied IS NULL OR tolerance_applied >= 0",
            name=op.f("ck_match_result_tolerance_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entry.id"],
            name=op.f("fk_match_result_ledger_entry_id_ledger_entry"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["settlement_line_id"],
            ["settlement_line.id"],
            name=op.f("fk_match_result_settlement_line_id_settlement_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_result")),
        sa.UniqueConstraint("ledger_entry_id", name="uq_match_result_ledger_entry_id"),
        sa.UniqueConstraint("settlement_line_id", name="uq_match_result_settlement_line_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_result")
    op.drop_index("ix_settlement_line_batch_match_state", table_name="settlement_line")
    op.drop_table("settlement_line")
    op.drop_table("settlement_batch")
    op.drop_index("ix_ledger_entry_account_code_booked_at", table_name="ledger_entry")
    op.drop_table("ledger_entry")
    # ### end Alembic commands ###
